Connection:
  type: 'sqlite'
  MySQL:
    host: '190.115.197.21'
    port: '3306'
    username: 'u6351_d2EEtdqZAM'
    password: 'l3Rkr439aR@p.aUsrXm2vQhx'
    database: 's6351_teste'

Preferences:
  max-tags-in-use: 3
