# [EN-US] There are two connection methods in this plugin,
# [EN-US] using SQLite or MySQL, if you don't have any database
# [EN-US] or don't know how to use MySQL, leave the sqlite option.
# [PT-BR] Existem dois métodos de conexão neste plugin,
# [PT-BR] usando SQLite ou MySQL, se você não tiver nenhum banco de dados
# [PT-BR] ou não sabe usar o MySQL, deixe a opção sqlite.
Connection:
  # sqlite;mysql
  type: 'sqlite'
  ## This is the MySQL database configuration.
  ## Use the data provided by your server, any information
  ## wrong in this process will stop the connection.
  MySQL:
    host: 'localhost'
    port: '3306'
    username: 'user'
    password: 'pass'
    database: 'database'

Preferences:
  # [en-US] The language of the plugin.
  # [pt-BR] A linguagem padrão do plugin.
  language: 'en-US'
  # [en-US] The default tags per use of the player.
  # [pt-BR] O padrão de tags por uso permitidas oa jogador.
  max-tags-in-use: 3
  # [en-US] The permission to use admin commands.
  # [pt-BR] A permissão para usar comandos de administrador.
  admin-permission: 'coretags.admin'
  # [en-US] The name and format of the economies.
  # [pt-BR] O nome e formato das economias.
  Economy:
    cash: '&6cash'
    coins: '&2coins'

Items:
  Tag:
    # [en-US] The item name. *Dont delete ;<nl>*
    # [pt-BR] O nome do item. *Não apague ;<nl>*
    # Format: itemID;data;displayName;<nl>
    using: '342;0;&7Tag: &e%format%;<nl>'
    owned: '342;0;&7Tag: &e%format%;<nl>'
    not-owned: '328;0;&7Tag: &e%format%;<nl>'
  Filters:
    # [en-US] The item name. *<nl> here, is used for create a new line in the lore.*
    # [pt-BR] O nome do item. *<nl> aqui, é usado para criar uma nova linha no lore.*
    # Format: itemID;data;displayName;lore
    filter: '145;0;&8Filter tags;<nl>&7Click to filter tags by rarity.'
    Equipped:
      default: '351;8;&8Show tags equipped;<nl>&7Click to view only equipped tags.'
      selected: '351;10;&aViewing tags equipped;<nl>&7Now you are viewing only equipped tags.'
    Bought:
      default: '351;8;&8Show owned tags;<nl>&7Click to view only owned tags.'
      selected: '351;10;&aViewing owned tags;<nl>&7Now you are viewing only owned tags.'
    Not-Bought:
      default: '351;8;&8View not owned tags;<nl>&7Click to view only not owned tags.'
      selected: '351;10;&aViewing not owned tags;<nl>&7Now you are viewing only not owned tags.'
    All:
      default: '351;8;&8View all tags;<nl>&7Click to view all tags.'
      selected: '351;10;&aViewing all tags;<nl>&7Now you are viewing all tags.'
  Inventories:
    next-page: '262;0;&aNext page;<nl>&7Click to navigate to next page.'
    previous-page: '262;0;&cPrevious page;<nl>&7Click to navigate to previous page.'
    back: '166;0;&cBack;<nl>&7Click to back.'

Format:
  # [en-US] The format of the tag in inventory.
  # [pt-BR] O formato da tag no inventário.
  Tag:
    information:
      - ''
      - '&7Information of this tag:'
      - ''
      - '&7Description:'
      - '%description%'
      - ''
      - '&7Format: &e%format%'
      - '&7Rarity: &f%rarity%'
      - '&7Price: &6$ &7%price% %type%'
  Rarity:
    name: '&7Rarity: %rarity%'
    information:
      - ''
      - '&7List only tags with this rarity.'
      - ''
      - '&7Actually, there are &f%amount% &7tags with this rarity.'
      - ''
      - '&aClick to filter tags by rarity.'